### ISSUE TITLE
webinar-checklist

### ISSUE THREAD

**Issue by sandesh2026** [DevTools-India/webinar-checklist#1]
Before webinar

*   [ ] Promo video
*   [ ] Social media Posts
*   [ ] Email signature
*   [ ] Website slider / announcement
*   [ ] Reminder emails

After Webinar

*    [ ]  Sharing the Recording link through emails
*    [ ]  Sharing the Recording link - Social media posts

**Comment by GaneshBabu-J** [comment]
@sandesh2026 we need to invite Kanthesh here. Can you do it

**Comment by sandesh2026** [comment]
Yeah sent the invitation

![](https://user-images.githubusercontent.com/38805340/107328656-0fc3ca80-6ad5-11eb-985d-d203561a09ed.png)
